name: A/mainline
on:
  push:
    paths:
      - 'A/**'
      - '.github/workflows/**'
    branches:
      - master
jobs:
  Test:
    uses: ./.github/workflows/A_pr.yml
  Report:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - run: echo Reporting
