name: A/mainline
on:
  push:
    paths:
      - 'A/**'
      - '.github/workflows/**'
    branches:
      - master
jobs:
  Test:
    uses: ./github/workflows/A_pr@master
  Report:
    runs-on: ubuntu-latest
    steps:
      - run: echo Reporting
