name: C/mainline
on:
  push:
    paths:
      - 'C/**'
      - '.github/workflows/**'
    branches:
      - master
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          cd C
          ./test
      - run: echo $PWD
