name: Testing project A
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          cd A
          ./test
      - run: echo $PWD
